### ISSUE TITLE
fs-path - high vulnerability for command injection

### ISSUE THREAD

**Issue by delrueba** [felixzapata/gulp-axe-webdriver#20]
Hi,

one of the dependencies has a high vulnerability, see https://hackerone.com/reports/324491

**Comment by felixzapata** [comment]
hello, thanks. I will take a look ASAP.

**Comment by felixzapata** [comment]
I've released a new version.

**Comment by hstandaert** [comment]
@felixzapata, thanks for updating the dependencies, but as stated in https://www.npmjs.com/advisories/661, the `fs-path` dependency should be removed since all versions are affected. 

(You could look into using the `fs` module instead: https://nodejs.org/api/fs.html#fs_fs_writefilesync_file_data_options)

**Comment by felixzapata** [comment]
@hstandaert done
