### ISSUE TITLE
Downgrade chromedriver

### ISSUE THREAD

**Issue by ffoodd** [felixzapata/gulp-axe-webdriver#7]
Hi there,

I'm already using this excellent plugin (itself using an awesome project, I love aXe <3) but since a few days I'm not able to install gulp-axe-webdriver because of its chromedriver dependency. It doesn't use npm proxy configuration correctly and therefore fails to download, causing gulp-axe-webdriver installation to fail.

There's already [an opened issue in chromedriver repository](https://github.com/giggio/node-chromedriver/commit/5ad68a36c3260760f1eb40d9c7906c6ea19c05b3).

So I was wondering if you dared downgrading chromedriver to its 2.25.2 version (a single patch version from current) to temporary resolve gulp-axe-webdriver installation behind a proxy?

Thanks a lot!

**Comment by felixzapata** [comment]
hi @ffoodd, let me take a look.

**Comment by ffoodd** [comment]
the opened issue in chromedriver is moving forward. FYI the latest working version behind a proxy is 2.25.1. Thanks for your attention!

**Comment by felixzapata** [comment]
ok, some weeks ago there was a problem with some version of the driver after Chrome 55 was published. The version of the driver should not be lower (I do not remember the version now) that this one.

**Comment by felixzapata** [comment]
I´ve released version 1.3.2

**Comment by ffoodd** [comment]
Thanks a lot, it works perfectly!!

**Comment by felixzapata** [comment]
You're welcome. Anyway, I will try to keep an eye over the issue.

**Comment by joseluisgraa** [comment]
Hi, I'm having this issue now behind a proxy, is there something I can do as a workaround? Or could this module be updated to use the latest chromedriver and see if it solves the problem? 
Thanks!
Edit: It has worked installing it globally so I will continue having a look at it tomorrow, it might be something to do with this laptop... :)

**Comment by felixzapata** [comment]
hi @joseluisgraa, ok let me know if you still have problems.

**Comment by joseluisgraa** [comment]
I'm still unable to install the plugin because of this issue with chromedriver. It lets me install version 2.25.1 of chromedriver globally but if I want it locally I can only do it using the latest version (or some of the latest), so when I try to install this plugin it fails as it specifies version 2.25.1. For protractor we are not installing this driver using npm, we have it in a specific folder and point to it in the protractor config file. Would that be possible with your plugin? Is there a way to specify the plugin location?

**Comment by felixzapata** [comment]
do you mean the location of the chromedriver plugin?
